directus:
  image: getdirectus/directus:6.4
  # namespace: directus
  # serviceAccount: directus
  role:
    create: true
    # name: directus
  secret:
    create: true
    # name: directus
  db:
    name: directus
    user: directus
    host: mysql.mysql.svc.cluster.local
    port: "3306"

  # Change required:
  hosts:
    - directus.local
