apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: {{ .Values.directusNamespace }}
  name: {{ template "directus.fullname" . }}
  labels:
    app: {{ template "directus.name" . }}
    chart: {{ template "directus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "directus.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "directus.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.directusServiceAccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.directusImage }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
