apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: {{ default (template "directus.fullname" .) .Values.directus.namespace }}
  name: {{ template "directus.fullname" . }}
  labels:
    app: {{ template "directus.name" . }}
    chart: {{ template "directus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "directus.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "directus.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ default (template "directus.fullname" .) .Values.directus.serviceAccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.directus.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ default (template "directus.fullname" .) .Values.directus.configMap.name }}
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: name: {{ default (template "directus.fullname" .) .Values.directus.secret.name }}
                  key: mysql_password
            - name: MYSQL_ENV_MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ default (template "directus.fullname" .) .Values.directus.configMap.name }}
                  key: mysql_database
            - name: MYSQL_PORT_3306_TCP_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ default (template "directus.fullname" .) .Values.directus.configMap.name }}
                  key: mysql_host
            - name: MYSQL_PORT_3306_TCP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ default (template "directus.fullname" .) .Values.directus.configMap.name }}
                  key: mysql_port
            - name: MYSQL_ENV_MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ default (template "directus.fullname" .) .Values.directus.configMap.name }}
                  key: mysql_user
            - name: MYSQL_ENV_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (template "directus.fullname" .) .Values.directus.secret.name }}
                  key: mysql_password
