apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.directusNamespace }}
  name: {{ template "directus.fullname" . }}
  labels:
    app: {{ template "directus.name" . }}
    chart: {{ template "directus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  tls:
    - hosts:
      - {{ .Values.directusHost }}
      secretName: {{ template "directus.fullname" . }}-tls
  rules:
    - {{ .Values.directusHost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "directus.fullname" . }}
              servicePort: http
