apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ default (include "directus.fullname" .) .Values.directus.namespace }}
  name: {{ template "directus.fullname" . }}
  labels:
    app: {{ template "directus.name" . }}
    chart: {{ template "directus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  tls:
  {{- range .Values.directus.hosts }}
    - hosts:
        - {{ . }}
      secretName: {{ . | replace "." "-" }}-tls
  {{- end }}
  rules:
  {{- range .Values.directus.hosts }}
    - {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "directus.fullname" . }}
              servicePort: http
  {{- end }}
