{{- if .Values.directus.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "directus.fullname" . }}
  namespace: {{ default (template "directus.fullname" .) .Values.directus.namespace }}
  labels:
    app: {{ template "directus.name" . }}
    chart: {{ template "directus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mysql_password: {{ .Files.Get ".password" | b64enc }}
{{- end }}
