apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ default (include "directus.fullname" .) .Values.directus.namespace }}
  name: {{ default (include "directus.fullname" .) .Values.directus.serviceAccount }}
  labels:
    app: {{ template "directus.name" . }}
    chart: {{ template "directus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
