apiVersion: v1
kind: Service
metadata:
  namespace: {{ default (template "directus.fullname" .) .Values.directus.namespace }}
  name: {{ template "directus.fullname" . }}
  labels:
    app: {{ template "directus.name" . }}
    chart: {{ template "directus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: "8080"
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "directus.name" . }}
    release: {{ .Release.Name }}
